version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: example_db
      MYSQL_USER: user1
      MYSQL_PASSWORD: password1
    volumes:
      # - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

# volumes:
#   db_data:
